apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 34.59.30.245.nip.io
  privateKey:
    algorithm: RSA
    size: 2048
  # Certificate will be renewed 30 days before expiry
  renewBefore: 720h # 30 days
