apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: tls-cipher-policy
  namespace: argocd
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external-http
  default:
    sslPolicy: gke-gateway-ssl-policy
