namespace: argocd
createNamespace: false

domains:
  - 34.111.216.1.nip.io

gateway:
  enabled: true
  name: external-http
  namespace_policy: All
  className: gke-l7-global-external-managed
  ipv4:
    enabled: true
    address: argocd-ipv4
    address_type: NamedAddress
  ipv6:
    enabled: false
    address: argocd-ipv6
    address_type: NamedAddress
  routes:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      port: 443
      protocol: HTTPS
      use_tls: true
      mode: Terminate
      include_cert: true

certificate:
  name: argocd-server-tls
  issuer: letsencrypt-prod
  staging: false
  use_gateway: true

tlsPolicy:
  enabled: true
  name: gke-gateway-ssl-policy
# cert-manager:
#   enabled: true
#   namespace: cert-manager
#   crds:
#     # This option decides if the CRDs should be installed
#     # as part of the Helm installation.
#     enabled: true
#   config:
#     enableGatewayAPI: true
