---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-ch1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  project: telemetry

  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
    helm:
      values: |-
        crds:
          enabled: true
          keep: true

        config:
          enableGatewayAPI: true
    chart: cert-manager
  destination:
    server: https://35.232.70.154
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
