apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https
  namespace: argocd
spec:
  parentRefs:
    - name: external-http
      namespace: argocd
  hostnames:
    - argo.gc1.mgt.stardust.es.net
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
