---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vmauth-config
  namespace: vm
spec:
  encryptedData:
    auth.yml: AgCBV27ebA1U2/Wu3ube249uG7R60ZnfLx6c0wBUkQ0Ryo1TOrGsbHK//zPpYrcPL7Ak9OODhcoQDzmO0RkI9hN2jHHUpYDOw0xwKFEJhWsJGBXC9J9MsUEH38zujY79FgBNXGmFskwcKwHrfLAUZQCQzqNy32UgQ8o9XCsA5eTe+EGes954xZzh8MUEIdIK4/V5otFA8TCuw0l9IdJbKWReAyfWvv0jmJBwteFGIl5tvHsiz45lkdybyfLI/e9fCZ7M3RdDa++tdlG/ZTsMw+dg6xVQyOOWT9weKmJ5lBQJ/VDtJVCGXMnOrJkW7uPnkxmPk4LjYbXLnAgShZJM796yHQbqC3vGDtXvs7tl07Ji1LqrnNvAvD1cT+hzmU6crx93tzuhNhAEMlyQLpiKjcQc83Xf80SiZwnIA89DL0wuCKlB+HlEdVHnqsYlp9TgsbqMtcG49m6xZVqMW2HF/q+k+yIEz38UnSuwej8bRk/8IT/Vc2tVQ2i/AG717PVzvOnv/yqnnz5dWM2+TqsgNVrjBmsKt+okXkUZjaK8w1suqAfb5dFz9XosnPtifv2NtHY9lboB9/76u8YG0O1BpRo/pXVkW37I+/u3rlTQD7ABNqU7CKlGLZPy7DTvKtFBSo5L7gkYC3NIWQ9G/qz7eLvEJUakB9v+jtMOoLVkK/aMVKXMajOYy74PsR1XKIMyU5F/7HNo875O6b1D1LPlGB0rmDVNZrjvI1gqSEm+1Pw4Fqdy5rmSALlkHoC71OxQZJazqS8Bhwojdm08QngRh8Ga8aZX8OHUj8SUTA3M2wKgeFIL58KZDnt/GCTct/F+ifzNzptKMJnd8qX2bNZ9dzHGpPo2hud1aesdq5u9aW6Om8L+jfgkW+1MQWn8Pkm/2k7tzOckillUdaRPLqWApUuT2oHFrQutoGlpPFSpZzRviobZqvtqW5wFyBc2R22aHxyFYQDJIrHA+A0RSI9hs6oE25urlSBhg8xNHUhORHDlzSVgPhu2+XI2ZwnyX53fLmV2JGo5XfSyzZmG5ZrwTJj0De/C/IVcR7JbNtu3RaaJisnFxWBWG5Y763rWlPmG0zw7yZZvlGbVHQmVE/SNdEQL4b1u2/WQhs/LnAuoaS8O8wlQE5Tpxz3ByUUl/Gc5/annbUn6cLiPrDc0a6ONJkOsa8OlOCffI9Qr4v5u/zKHBi0tohnEFMtF/HtV8ZMevyOjvSzc8AJvMEofbsmjDoo5HPf2r/IGxiqUv6dI1OIKiZTS5GKtyaxu/bCMU5V8l/ORJS97nzYVjqNGNFqKip8/0eqJ41SdPNKH2QvZXsNhe2E7NA+i/S5XSNWYZEblO4WnxRUJ7+dyMUzQqlTUFvMNmmI59CrD9FUi68ulZ778mAohVA3NyP8f4uL0KV46NFX0dJsAncD1a3yWnyYSAhvVA3HioBw=
  template:
    metadata:
      name: vmauth-config
      namespace: vm
    type: Opaque
