namespace: clickhouse
envoy:
  createNamespace: false
  enabled: true
  namespace: envoy-gateway-system

domains:
  - 34.172.208.101.nip.io

gateway:
  className: envoy
  ipv4:
    address: 34.172.208.101
  routes:
    - name: clickhouse-secure
      port: 9440
      mode: Passthrough
      protocol: TLS
      use_tls: true
      include_cert: false
    - name: http
      port: 80
      protocol: HTTP
    - name: ssl-validation
      port: 8443
      protocol: TLS
      use_tls: true
      mode: Passthrough
      include_cert: false
    - name: clickhouse-https
      port: 443
      protocol: HTTPS
      use_tls: true
      mode: Terminate
      include_cert: true

tlsPolicy:
  enabled: false
