namespace: vm
createNamespace: false

domains:
  - 34.110.238.189.nip.io
envoy:
  enabled: false

gateway:
  enabled: true
  name: external-http
  namespace_policy: All
  className: gke-l7-global-external-managed
  ipv4:
    enabled: true
    address: vm-prod
    address_type: NamedAddress
  ipv6:
    enabled: false
  routes:
    - name: http
      port: 80
      protocol: HTTP
    - name: https-vm
      port: 443
      protocol: HTTPS
      use_tls: true
      mode: Terminate
      include_cert: true

certificate:
  name: vm-server-tls
  issuer: letsencrypt-prod
  staging: false
  use_gateway: true

tlsPolicy:
  enabled: true
  name: gke-gateway-ssl-policy
